Se agregan comandos para cambiar el tema de escritorio y LightDM.

diff --git a/conf/sbin/changehostname b/conf/sbin/changehostname
--- a/conf/sbin/changehostname
+++ b/conf/sbin/changehostname
@@ -5,14 +5,14 @@ NAME="$1"
 
 # Check for permissions errors
 if [ `id -u` != 0 ]; then
-	echo "[ERROR] Este script requiere ser ejecutado como root."
-	exit 1
+    echo "[ERROR] Este script requiere ser ejecutado como root."
+    exit 1
 fi
 
 # Check for argument errors
 if [ -z "$NAME" ]; then
-	echo "[ERROR] Por favor escriba el nuevo nombre del sistema."
-	exit 1
+    echo "[ERROR] Por favor escriba el nuevo nombre del sistema."
+    exit 1
 fi
 
 echo "$NAME" > /etc/hostname
